export const APP_LOAD = 'APP_LOAD';
export const INITIAL_CONNECT_ATTEMPT = 'INITIAL_CONNECT_ATTEMPT';
export const QUEUE_JOINED = 'QUEUE_JOINED';
export const PARTNER_FOUND = 'PARTNER_FOUND';
export const CONNECTION_STARTED = 'CONNECTION_STARTED';
export const NEW_PARTNER_REQUESTED = 'NEW_PARTNER_REQUESTED';
